### ISSUE TITLE
Schema dump fails if rails project path has a space in it

### ISSUE THREAD

**Issue by vsubramanian** [jakeonrails/fix-db-schema-conflicts#14]
```
Dumping database schema with fix-db-schema-conflicts gem
Error: No such file or directory: /Users/vasanth/Active
$ pwd
/Users/vasanth/Active Projects/project
```

**Comment by jakeonrails** [comment]
Hey thanks for reporting and submitting the fix!

Version 2.0.1 is now released including your patch if you want to bump the version in your Gemfiles.

**Comment by jakeonrails** [comment]
P.S. I also added you to the Readme as a contributor. :)

**Comment by vsubramanian** [comment]
@jakeonrails 👍  thanks very much
