### ISSUE TITLE
Support Rubocop >= 0.49.0

### ISSUE THREAD

**Issue by amckinnell** [jakeonrails/fix-db-schema-conflicts#22]
Some of the cops used to autocorrect `db/schema.rb` have been moved to another [department](https://github.com/bbatsov/rubocop/pull/4278) as of Rubocop `0.49.0`.

See my [pull request](https://github.com/jakeonrails/fix-db-schema-conflicts/pull/21) for a possible solution.

**Comment by amckinnell** [comment]
Since the [pull request](https://github.com/jakeonrails/fix-db-schema-conflicts/pull/21) has been merged, this issue can be closed.

**Comment by jakeonrails** [comment]
Thanks for the reminder! :)
