### ISSUE TITLE
Column sorting improvements

### ISSUE THREAD

**Issue by hurrycaner** [jakeonrails/fix-db-schema-conflicts#24]
Would be nice to have some sorting intelligence behind this gem.
Take a look at this doc:
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/development/ordering_table_columns.md

**Comment by jakeonrails** [comment]
This is an interesting idea but it's not something I'm going to be able to spend time on building.

I don't believe that it would improve performance for any but the most unique users. The only times we would typically build an entire database using `schema.rb` are when we load up test db before running specs. I believe most folks using this gem will not have incredibly large test suites (database size-wise) where this feature could actually impact them.
