### ISSUE TITLE
Rubocop's Layout/AlignHash has been renamed to Layout/HashAlignment

### ISSUE THREAD

**Issue by rhymes** [jakeonrails/fix-db-schema-conflicts#39]
> Error: The `Layout/AlignHash` cop has been renamed to `Layout/HashAlignment`.
(obsolete configuration found in /Users/rhymes/.rvm/gems/ruby-2.6.5/gems/fix-db-schema-conflicts-3.0.3/.rubocop_schema.53.yml, please update it)

Rubocop 0.78 contains this change, see https://github.com/rubocop-hq/rubocop/commit/7ab80f9e1d262ff34fe4a1ea1a752a22bec26310

**Comment by takmar** [comment]
This will be resolved by merging [this PR](https://github.com/jakeonrails/fix-db-schema-conflicts/pull/43).

**Comment by bak1an** [comment]
Resolved with #41
