### ISSUE TITLE
Whitespace after fieldname

### ISSUE THREAD

**Issue by timdiggins** [jakeonrails/fix-db-schema-conflicts#6]
I'm not sure why but after upgrading to latest (from 1.0.1) along with some other library upgrades, the whitespace after the fieldtype is no longer removed, e.g:

e.g. since the latest version it allows:
```
  create_table "absences", force: true do |t|
    t.string  "code"
    t.date    "date"
  end
```

whereas before this was normalized to
```
  create_table "absences", force: true do |t|
    t.string "code"
    t.date "date"
  end
```

The unnormalized version obscures the location of changes through spurious whitespace (e.g. if you add a field with a longer length fieldtype to a model)

I've looked at the code and I can't see where that was being removed. I've got a PR that removes this with a tweaked sed command if that's useful.

BTW you should maybe note in the README that this will only work on OSX and FreeBSD (because of the use of sed -E -- not available on GNU/linux and obvs windows)

**Comment by jakeonrails** [comment]
Hi, thank you for the PR and the issue. Thanks for being patient - didn't mean to take so long to get back to you.

In order to figure out what exactly caused the issue, could you post your Gemfile.lock? Ideally maybe even a before/after of the other libraries? I've tried to duplicate this locally but I can't seem to get it to do what you're describing.

That said, you're fix seem to work fine so I'm probably going to merge it anyways, but I'd like to at least know what's causing the issue so I can troubleshoot/keep   it in mind for the future.

**Comment by timdiggins** [comment]
No prob. I've attached the last-known-good and the first bad Gemfile.lock in the attached zip.

[Gemfile.locks.zip](https://github.com/jakeonrails/fix-db-schema-conflicts/files/185061/Gemfile.locks.zip)

I'm wondering if the change is caused by the addition of default "AllowExtraSpacing" default true in https://github.com/bbatsov/rubocop/commit/8917dc189dfcd8eac82d02613954f132635a7279

**Comment by jakeonrails** [comment]
Cool, you were right, it looks like. The new default was breaking things.

I've made the following changes to `master`:

  - Upgrade Rubocop to get major performance boost
  - Add support for sorting of extensions
  - Fix spacing regression introduced by Rubocop upgrade
  - Add test suite and an integration test

Please check it out and LMK what you think! Hopefully that upgrade to Rubocop doesn't add any new surprises! It's gonna make your migrations much faster!

**Comment by jakeonrails** [comment]
P.S. Version is now 1.2.1 if you wanna rebundle!

**Comment by timdiggins** [comment]
@jakeonrails that's great and thanks for the contribution listing. It's also great to see you've added some functional tests -- I was just about to suggest that. 

I found that in my manual tests the existing sed command was actually having no impact, which is why my PR changed the sed command, but your fix is the right one.
So I'm wondering if the sed command is still doing anything -- have you tried removing it experimentally (especially now you've got some tests)?

**Comment by jakeonrails** [comment]
Great suggestion. I remove the sed line, and a non-op line that was also in that rake task. Bumped version to 1.2.2, so if you have a non-sed system it should work for you now! Let me know if there's any issues. Thank you!
