### ISSUE TITLE
Postgres extensions not sorted

### ISSUE THREAD

**Issue by mjonas87** [jakeonrails/fix-db-schema-conflicts#8]
Sorting of postgres extensions would be awesome. Obviously its not as much of an issue as columns, but seeing as you've solved that already ;)

![screen shot 2016-03-22 at 10 34 43 am](https://cloud.githubusercontent.com/assets/1400552/13961426/dfce6a78-f019-11e5-92d0-1ec2b848852d.png)

**Comment by jakeonrails** [comment]
I'm sorry Matt, looks like I somehow missed this notification on my dashboard. If you'd like to take a crack at a PR for this, it'd be swell and I'm happy to merge and bump the version.

**Comment by jakeonrails** [comment]
I'll be able to ship this sometime soon though, like the next couple weeks or so if you don't have time.

**Comment by jakeonrails** [comment]
Matt, I think the latest version of this gem now supports sorting of extensions. 2.0.0. Give it a shot?
