### ISSUE TITLE
Deprecation warnings in Rails 5

### ISSUE THREAD

**Issue by jensljungblad** [jakeonrails/fix-db-schema-conflicts#9]
In Rails 5, `alias_method_chain` has been deprecated. It's being used in `lib/fix_db_schema_conflicts/schema_dumper.rb`:

```ruby
def extensions_with_sorting(*args)
  with_sorting do
    extensions_without_sorting(*args)
  end
end
alias_method_chain :extensions, :sorting

def table_with_sorting(*args)
  with_sorting do
    table_without_sorting(*args)
  end
end
alias_method_chain :table, :sorting
```

**Comment by jakeonrails** [comment]
Thanks for reporting. I won't be able to hit this right away, sadly.

Anyone who wants to take this on before I get around to it may find this useful: http://www.justinweiss.com/articles/rails-5-module-number-prepend-and-the-end-of-alias-method-chain/

There are specs, so this should be low hanging fruit for anyone who wants to contribute!

**Comment by jensljungblad** [comment]
Is support for Ruby < 2.0 still required? If so, how would you go about this? A conditional that checks the Ruby version in the code?

**Comment by jakeonrails** [comment]
A conditional would work, but I would merge a PR without support for < 2.0, since 1.9 is unsupported as of 2014.
